name: UKHO.UIAutomationFramework_3.$(date:yy)$(DayOfYear)$(rev:.r)

resources:
- repo: self
  clean: all

trigger:
  branches:
    include:
      - refs/heads/*

pool:
  name: NautilusBuild

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@1
  displayName: 'Apply-AssemblyVersionAndDefaults'
  inputs:
    scriptName: 'DeploymentScripts/Apply-AssemblyVersionAndDefaults.ps1'

    arguments: '-buildNumber "$(Build.BuildNumber)" -solutionDirectory "$(Build.SourcesDirectory)"'
