name: UKHO.UIAutomationFramework_4.$(date:yy)$(DayOfYear)$(rev:.r)

resources:
- repo: self
  clean: true

workspace:
   clean: all

trigger:
  branches:
    include:
      - refs/heads/*

pool:
  name: NautilusBuild

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Shared Services Live'
    keyVaultName: 'm-centralcertificates-kv'
    secretsFilter: "UKHOCodeSigningExpAug2027"
  displayName: Download secrets from Azure Key Vault

- powershell: |
    ./DeploymentScripts/New-PfxFromBase64EncodedString.ps1 `
      -pfxString $(UKHOCodeSigningExpAug2027)
  env:
    pfxPassword : $(pfxPassword)
  displayName: Generate PFX

- task: PowerShell@2
  displayName: 'Apply-AssemblyVersionAndDefaults'
  inputs:
    targetType: 'filePath'
    filePath: 'DeploymentScripts/Apply-AssemblyVersionAndDefaults.ps1'
    arguments: '-buildNumber "$(Build.BuildNumber)" -solutionDirectory "$(Build.SourcesDirectory)"'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6.x'
  inputs:
    versionSpec: 6.x
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**\*.sln'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '**\*.sln'
    configuration: 'Release'
    maximumCpuCount: true

- task: DotNetCoreCLI@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: UKHO.UIAutomationFramework/UKHO.SpecflowSessionDependencyInjection/UKHO.SpecflowSessionDependencyInjection.nuspec
    includeSymbols: true
    packDirectory: '$(Build.ArtifactStagingDirectory)'

- powershell: |
    nuget sign '$(Build.ArtifactStagingDirectory)\*.nupkg' -CertificatePath $(pfxLocation) -Timestamper 'http://rfc3161timestamp.globalsign.com/advanced' -CertificatePassword $env:PFX_PASSWORD
  env:
    PFX_PASSWORD: $(pfxPassword)
  displayName: 'NuGet Sign'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
