name: UKHO.UIAutomationFramework_3.$(date:yy)$(DayOfYear)$(rev:.r)

resources:
- repo: self
  clean: all

trigger:
  branches:
    include:
      - refs/heads/*

pool:
  name: NautilusBuild

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure Live'
    keyVaultName: 'UKHOKeyvault'
    secretsFilter: "UKHOCodeSigningCert"
  displayName: Download secrets from Azure Key Vault

- powershell: |
    ./generatePfx.ps1 `
      -pfxString $(UKHOCodeSigningCert) 
  env:
    pfxPassword : $(password)
  displayName: Generate PFX

- task: PowerShell@1
  displayName: 'Apply-AssemblyVersionAndDefaults'
  inputs:
    scriptName: 'DeploymentScripts/Apply-AssemblyVersionAndDefaults.ps1'

    arguments: '-buildNumber "$(Build.BuildNumber)" -solutionDirectory "$(Build.SourcesDirectory)"'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.x'
  inputs:
    versionSpec: 4.9.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**\*.sln'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '**\*.sln'
    configuration: 'Release'
    maximumCpuCount: true

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: UKHO.UIAutomationFramework/UKHO.SpecflowSessionDependencyInjection/UKHO.SpecflowSessionDependencyInjection.csproj
    includeReferencedProjects: true
    includeSymbols: true
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
