<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyTitle>UKHO.SpecflowSessionDependencyInjection</AssemblyTitle>
    <AssemblyCompany>UK Hydrographic Office</AssemblyCompany>
    <AssemblyProduct>UKHO.SpecflowSessionDependencyInjection</AssemblyProduct>
    <AssemblyCopyright>Copyright © UK Hydrographic Office 2025</AssemblyCopyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UKHO.SeleniumWebDriver\UKHO.SeleniumDriver.csproj" />
    <ProjectReference Include="..\UKHO.WebDriverInterface\UKHO.WebDriverInterface.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\UKHO.SeleniumWebDriver\bin\$(Configuration)\$(TargetFramework)\UKHO.SeleniumDriver.dll">
      <Pack>true</Pack>
      <PackagePath>lib\$(TargetFramework);ref\$(TargetFramework)</PackagePath>
    </None>
    <None Include="..\UKHO.WebDriverInterface\bin\$(Configuration)\$(TargetFramework)\UKHO.WebDriverInterface.dll">
      <Pack>true</Pack>
      <PackagePath>lib\$(TargetFramework);ref\$(TargetFramework)</PackagePath>
    </None>
  </ItemGroup>
</Project>
