<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyTitle>UKHO.WebDriverInterface</AssemblyTitle>
    <AssemblyCompany>UK Hydrographic Office</AssemblyCompany>
    <AssemblyProduct>UKHO.WebDriverInterface</AssemblyProduct>
    <AssemblyCopyright>Copyright © UK Hydrographic Office 2025</AssemblyCopyright>
  </PropertyGroup>
</Project>
